#!/usr/bin/env python3
"""Generate/check private Hostap symbol names from the component archive, locally.
Run --generate once against an unprefixed build; --check validates the final build.
The prefix header is committed so consumers do not need nm at configure time.
"""
import argparse,re,subprocess
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--nm',required=True);p.add_argument('--archive',required=True)
a=p.add_mutually_exclusive_group(required=True);a.add_argument('--generate',action='store_true');a.add_argument('--check',action='store_true')
args=p.parse_args();output=subprocess.check_output([args.nm,'-g','--defined-only',args.archive],text=True)
symbols=set()
for line in output.splitlines():
 m=re.fullmatch(r'[0-9a-fA-F]+\s+[A-Z]\s+([A-Za-z_][A-Za-z0-9_]*)',line.strip())
 if m and m[1]!='AX900_EVENTS' and not m[1].startswith(('ax900_','ax_','_binary_')):symbols.add(m[1])
if args.check:
 if symbols:raise SystemExit('Unisolated symbols: '+', '.join(sorted(symbols)))
 print('Supplicant symbols isolated')
else:
 target=Path(__file__).resolve().parents[1]/'components/ax900/ax900_symbols.h'
 target.write_text('// SPDX-License-Identifier: Apache-2.0\n// Generated by tools/supplicant_symbols.py; private to this component.\n#pragma once\n'+''.join(f'#define {name} ax900_priv_{name}\n' for name in sorted(symbols)))
 print(f'Isolated {len(symbols)} supplicant symbols')
